### ISSUE TITLE
wrong return value

### ISSUE THREAD

**Issue by mbiegert** [samuelsadok/fibre#1]
in the file protocol.hpp, starting from line 74:
```
template<>
inline size_t read_le<uint8_t>(uint8_t* value, const uint8_t* buffer) {
    *value = buffer[0];
    return 2;
}
```
Shouldn't this be one, as one byte is read from the buffer? The same goes for line 39 in the corresponding write function.

**Comment by samuelsadok** [comment]
Yes, you're correct, good catch.
I just pushed a fix on master.
